/**
 * ARMSTRONG MANIFEST — SINGLE SOURCE OF TRUTH (V2)
 * 
 * Phase 6 Governance Schema with execution_mode, side_effects, and versioning.
 * Defines all Armstrong actions, their permissions, zones, and billing metadata.
 * 
 * RULES:
 * 1. All actions must be declared here
 * 2. Zone field determines availability (Z2 = Portal, Z3 = Websites)
 * 3. execution_mode determines confirmation requirements (K3 compliant)
 * 4. Changes require explicit approval + version bump
 * 
 * K3 ENFORCEMENT:
 * - execution_mode='execute' only allowed if: risk_level='low' AND cost_model='free'
 *   AND (data_scopes_write=[] OR writes are internal-only, e.g. ['widgets'])
 * - Interne Widget-Writes gelten NICHT als schutzbeduerftiger Schreibzugriff (keine externen Konsequenzen)
 * 
 * K4 ENFORCEMENT:
 * - execution_mode='draft_only' must not write to SSOT tables directly
 */

import type {
  ArmstrongActionV2,
  ArmstrongZone,
  ExecutionMode,
  RiskLevel,
  CostModel,
  CostUnit,
  ActionStatus,
  validateAllActions,
} from '@/types/armstrong';

// Re-export types for backwards compatibility
export type { ArmstrongActionV2, ArmstrongZone, ExecutionMode, RiskLevel, CostModel };

// Legacy type alias for gradual migration
export type ArmstrongAction = ArmstrongActionV2;

// =============================================================================
// TOP 30 MVP ACTION CODES (Phase 6 Content Blueprints)
// =============================================================================

/**
 * TOP_30_MVP_ACTION_CODES — Core set of 30 actions for MVP.
 * Selected based on:
 * - Essential functionality coverage (Packs A-F, H)
 * - K3/K4 compliance verified
 * - Cost model validated
 */
export const TOP_30_MVP_ACTION_CODES = [
  // Pack A: Core (6)
  'ARM.GLOBAL.EXPLAIN_TERM',
  'ARM.GLOBAL.FAQ',
  'ARM.GLOBAL.HOW_IT_WORKS',
  'ARM.GLOBAL.WEB_SEARCH',
  'ARM.GLOBAL.SUMMARIZE_TEXT',
  'ARM.GLOBAL.DRAFT_MESSAGE',
  
  // Pack B: Dashboard (5)
  'ARM.MOD00.CREATE_TASK',
  'ARM.MOD00.CREATE_REMINDER',
  'ARM.MOD00.CREATE_NOTE',
  'ARM.MOD00.CREATE_IDEA',
  'ARM.MOD00.CREATE_PROJECT',
  
  // Pack C: DMS (4)
  'ARM.MOD03.SEARCH_DOC',
  'ARM.MOD03.EXPLAIN_UPLOAD',
  'ARM.MOD03.LINK_DOC',
  'ARM.MOD03.EXTRACT_DOC',
  
  // Pack D: Immobilien (6)
  'ARM.MOD04.EXPLAIN_MODULE',
  'ARM.MOD04.VALIDATE_PROPERTY',
  'ARM.MOD04.CREATE_PROPERTY',
  'ARM.MOD04.CREATE_UNIT',
  'ARM.MOD04.CALCULATE_KPI',
  'ARM.MOD04.DATA_QUALITY_CHECK',
  
  // Pack E: Finanzierung (4)
  'ARM.MOD07.EXPLAIN_SELBSTAUSKUNFT',
  'ARM.MOD07.DOC_CHECKLIST',
  'ARM.MOD07.PREPARE_EXPORT',
  'ARM.MOD07.VALIDATE_READINESS',
  
  // Pack F: Investment (4)
  'ARM.MOD08.ANALYZE_FAVORITE',
  'ARM.MOD08.RUN_SIMULATION',
  'ARM.MOD08.CREATE_MANDATE',
  'ARM.MOD08.WEB_RESEARCH',
  
  // Pack H: KB (1)
  'ARM.KB.CREATE_RESEARCH_MEMO',
  
  // Pack I: Projekte (2)
  'ARM.MOD13.CREATE_DEV_PROJECT',
  'ARM.MOD13.EXPLAIN_MODULE',
  
  // Pack J: Website Builder (2)
  'ARM.MOD21.GENERATE_WEBSITE',
  'ARM.MOD21.PUBLISH',
] as const;

export type Top30MvpActionCode = typeof TOP_30_MVP_ACTION_CODES[number];

/**
 * Check if action is in Top 30 MVP set
 */
export function isTop30MvpAction(actionCode: string): boolean {
  return TOP_30_MVP_ACTION_CODES.includes(actionCode as Top30MvpActionCode);
}

// =============================================================================
// ZONE 3 ALLOWED ACTIONS (Public/Unauthenticated)
// =============================================================================

export const ZONE3_ALLOWED_ACTION_CODES = [
  // Explanations
  'ARM.GLOBAL.EXPLAIN_TERM',
  'ARM.GLOBAL.FAQ',
  
  // Public Calculators
  'ARM.PUBLIC.RENDITE_RECHNER',
  'ARM.PUBLIC.TILGUNG_RECHNER',
  'ARM.PUBLIC.BELASTUNG_RECHNER',
  
  // Lead Capture (no data storage, forwarding only)
  'ARM.PUBLIC.CONTACT_REQUEST',
  'ARM.PUBLIC.NEWSLETTER_SIGNUP',
  
  // Listing Info (published only)
  'ARM.PUBLIC.EXPLAIN_LISTING',
  'ARM.PUBLIC.COMPARE_LISTINGS',
] as const;

export type Zone3ActionCode = typeof ZONE3_ALLOWED_ACTION_CODES[number];

// =============================================================================
// ACTIONS REGISTRY (V2 Schema)
// =============================================================================

export const armstrongActions: ArmstrongActionV2[] = [
  // ===========================================================================
  // GLOBAL ACTIONS (Available in Z2 and Z3)
  // ===========================================================================
  {
    action_code: 'ARM.GLOBAL.EXPLAIN_TERM',
    title_de: 'Begriff erklären',
    description_de: 'Erklärt Immobilien- und Finanzierungsbegriffe verständlich',
    zones: ['Z2', 'Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['knowledge_base'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'tool_call', endpoint: null, tool_name: 'search_knowledge' },
    ui_entrypoints: ['/portal', '/kaufy', '/miety', '/sot', '/futureroom'],
    audit_event_type: 'ARM_EXPLAIN_TERM',
    status: 'active',
  },
  {
    action_code: 'ARM.GLOBAL.FAQ',
    title_de: 'FAQ beantworten',
    description_de: 'Beantwortet häufig gestellte Fragen zu Plattform und Prozessen',
    zones: ['Z2', 'Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['knowledge_base'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal', '/kaufy', '/miety', '/sot', '/futureroom'],
    audit_event_type: 'ARM_FAQ',
    status: 'active',
  },
  {
    action_code: 'ARM.GLOBAL.HOW_IT_WORKS',
    title_de: 'Modul-Onboarding',
    description_de: 'Erklärt wie ein Modul funktioniert und führt durch erste Schritte',
    zones: ['Z2'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['routes_manifest', 'knowledge_base'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_HOW_IT_WORKS',
    status: 'active',
  },
  {
    action_code: 'ARM.GLOBAL.WEB_SEARCH',
    title_de: 'Web-Recherche',
    description_de: 'Recherchiert im Web nach aktuellen Informationen (mit Quellennachweis)',
    zones: ['Z2'],
    module: null,
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: ['external_api_call', 'credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 5,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_WEB_SEARCH',
    status: 'active',
  },

  // ===========================================================================
  // PUBLIC ACTIONS (Zone 3 - Lead Capture)
  // ===========================================================================
  {
    action_code: 'ARM.PUBLIC.RENDITE_RECHNER',
    title_de: 'Rendite berechnen',
    description_de: 'Berechnet Brutto-, Netto- und Eigenkapitalrendite',
    zones: ['Z2', 'Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'tool_call', endpoint: null, tool_name: 'calculate_investment' },
    ui_entrypoints: ['/kaufy', '/portal/investments'],
    audit_event_type: 'ARM_CALCULATE_YIELD',
    status: 'active',
  },
  {
    action_code: 'ARM.PUBLIC.TILGUNG_RECHNER',
    title_de: 'Tilgung berechnen',
    description_de: 'Berechnet Tilgungsplan und Restschuld',
    zones: ['Z2', 'Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'tool_call', endpoint: null, tool_name: 'calculate_investment' },
    ui_entrypoints: ['/kaufy', '/portal/finanzierung'],
    audit_event_type: 'ARM_CALCULATE_AMORTIZATION',
    status: 'active',
  },
  {
    action_code: 'ARM.PUBLIC.BELASTUNG_RECHNER',
    title_de: 'Monatliche Belastung berechnen',
    description_de: 'Berechnet die monatliche Netto-Belastung nach Steuern',
    zones: ['Z2', 'Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'tool_call', endpoint: null, tool_name: 'calculate_investment' },
    ui_entrypoints: ['/kaufy', '/portal/investments'],
    audit_event_type: 'ARM_CALCULATE_BURDEN',
    status: 'active',
  },
  {
    action_code: 'ARM.PUBLIC.CONTACT_REQUEST',
    title_de: 'Kontaktanfrage',
    description_de: 'Leitet eine Kontaktanfrage an das Lead-System weiter',
    zones: ['Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: 'CONSENT_CONTACT',
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: ['creates_lead_record', 'sends_notification'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-lead-inbox' },
    ui_entrypoints: ['/kaufy', '/miety', '/sot', '/futureroom'],
    audit_event_type: 'ARM_CONTACT_REQUEST',
    status: 'active',
  },
  {
    action_code: 'ARM.PUBLIC.NEWSLETTER_SIGNUP',
    title_de: 'Newsletter anmelden',
    description_de: 'Meldet für den Newsletter an',
    zones: ['Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: 'CONSENT_NEWSLETTER',
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: ['creates_subscriber_record'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-lead-inbox' },
    ui_entrypoints: ['/kaufy', '/miety', '/sot', '/futureroom'],
    audit_event_type: 'ARM_NEWSLETTER_SIGNUP',
    status: 'active',
  },
  {
    action_code: 'ARM.PUBLIC.EXPLAIN_LISTING',
    title_de: 'Objekt erklären',
    description_de: 'Erklärt Details eines öffentlichen Inserats',
    zones: ['Z2', 'Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['listings_published'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/kaufy', '/portal/investments'],
    audit_event_type: 'ARM_EXPLAIN_LISTING',
    status: 'active',
  },
  {
    action_code: 'ARM.PUBLIC.COMPARE_LISTINGS',
    title_de: 'Objekte vergleichen',
    description_de: 'Vergleicht mehrere Inserate nach Kennzahlen',
    zones: ['Z2', 'Z3'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['listings_published'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/kaufy', '/portal/investments'],
    audit_event_type: 'ARM_COMPARE_LISTINGS',
    status: 'active',
  },

  // ===========================================================================
  // MOD-02: KI OFFICE ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD02.SEND_LETTER',
    title_de: 'Brief absenden',
    description_de: 'Sendet einen vorbereiteten Brief per E-Mail, Fax oder Post',
    zones: ['Z2'],
    module: 'MOD-02',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['letter_drafts', 'contacts'],
    data_scopes_write: ['letter_sent'],
    side_effects: ['modifies_letter_sent', 'sends_external_communication'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-letter-send' },
    ui_entrypoints: ['/portal/office/brief'],
    audit_event_type: 'ARM_LETTER_SEND',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD02.WA_SEND_REPLY',
    title_de: 'WhatsApp Antwort senden',
    description_de: 'Sendet eine Antwort über WhatsApp Business an einen Kontakt',
    zones: ['Z2'],
    module: 'MOD-02',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['whatsapp_conversations', 'whatsapp_messages'],
    data_scopes_write: ['whatsapp_messages'],
    side_effects: ['sends_external_communication'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-whatsapp-send' },
    ui_entrypoints: ['/portal/office/whatsapp'],
    audit_event_type: 'ARM_WA_SEND_REPLY',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD02.WA_COMMAND_EXECUTE',
    title_de: 'Owner-Control Befehl ausführen',
    description_de: 'Verarbeitet einen WhatsApp-Befehl vom Owner und führt interne Aktionen sofort aus, externe als Widget zur Freigabe',
    zones: ['Z2'],
    module: 'MOD-02',
    risk_level: 'low',
    execution_mode: 'execute', // Runtime entscheidet: intern=sofort, extern=Widget zur Freigabe
    requires_consent_code: null,
    roles_allowed: ['org_admin'],
    data_scopes_read: ['whatsapp_messages', 'armstrong_command_events'],
    data_scopes_write: ['dashboard_widgets', 'letter_drafts', 'armstrong_command_events'],
    side_effects: ['creates_widget', 'creates_draft'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal/office/whatsapp'],
    audit_event_type: 'ARM_WA_COMMAND_EXECUTE',
    status: 'active',
  },

  // ===========================================================================
  // MOD-14: COMMUNICATION PRO — RECHERCHE ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD14.RESEARCH_FREE',
    title_de: 'Allgemeine Recherche',
    description_de: 'Führt eine kostenlose Web-Recherche durch und liefert eine strukturierte Zusammenfassung',
    zones: ['Z2'],
    module: 'MOD-14',
    risk_level: 'low',
    execution_mode: 'execute',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['research_sessions', 'research_results'],
    side_effects: ['external_api_call'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-research-engine' },
    ui_entrypoints: ['/portal/communication-pro/recherche'],
    audit_event_type: 'ARM_RESEARCH_FREE',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD14.RESEARCH_PRO',
    title_de: 'Profi-Kontaktrecherche',
    description_de: 'Sucht professionelle Kontakte über Apollo und liefert Kandidatenliste',
    zones: ['Z2'],
    module: 'MOD-14',
    risk_level: 'low',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['research_sessions', 'contact_candidates'],
    side_effects: ['external_api_call', 'credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-research-pro-contacts' },
    ui_entrypoints: ['/portal/communication-pro/recherche'],
    audit_event_type: 'ARM_RESEARCH_PRO',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD14.IMPORT_CANDIDATES',
    title_de: 'Kontakte übernehmen',
    description_de: 'Übernimmt ausgewählte Kontakt-Kandidaten ins zentrale Kontaktbuch (1 Credit/Kontakt)',
    zones: ['Z2'],
    module: 'MOD-14',
    risk_level: 'low',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['contact_candidates', 'contacts'],
    data_scopes_write: ['contacts', 'contact_candidates', 'credit_ledger'],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-contacts-import' },
    ui_entrypoints: ['/portal/communication-pro/recherche'],
    audit_event_type: 'ARM_IMPORT_CANDIDATES',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD14.DEDUPE_SUGGEST',
    title_de: 'Duplikatprüfung',
    description_de: 'Prüft ob ein Kontakt-Kandidat bereits im Kontaktbuch existiert',
    zones: ['Z2'],
    module: 'MOD-14',
    risk_level: 'low',
    execution_mode: 'execute',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['contact_candidates', 'contacts'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/communication-pro/recherche'],
    audit_event_type: 'ARM_DEDUPE_SUGGEST',
    status: 'active',
  },

  // ===========================================================================
  // MOD-03: DMS ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD03.SEARCH_DOC',
    title_de: 'Dokument suchen',
    description_de: 'Durchsucht das DMS nach Dokumenten',
    zones: ['Z2'],
    module: 'MOD-03',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['storage_nodes', 'documents'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'rpc', endpoint: 'search_documents' },
    ui_entrypoints: ['/portal/dms'],
    audit_event_type: 'ARM_DOC_SEARCH',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD03.EXPLAIN_UPLOAD',
    title_de: 'Upload-Workflow erklären',
    description_de: 'Erklärt wie Dokumente hochgeladen und organisiert werden',
    zones: ['Z2'],
    module: 'MOD-03',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['knowledge_base'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/dms'],
    audit_event_type: 'ARM_EXPLAIN_UPLOAD',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD03.LINK_DOC',
    title_de: 'Dokument verknüpfen',
    description_de: 'Verknüpft ein Dokument mit einer Immobilie oder Entität',
    zones: ['Z2'],
    module: 'MOD-03',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: ['org_admin', 'org_member'],
    data_scopes_read: ['storage_nodes', 'properties'],
    data_scopes_write: ['document_links'],
    side_effects: ['modifies_document_links'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'rpc', endpoint: 'link_document_to_entity' },
    ui_entrypoints: ['/portal/dms', '/portal/immobilien'],
    audit_event_type: 'ARM_DOC_LINK',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD03.EXTRACT_DOC',
    title_de: 'Dokument extrahieren',
    description_de: 'Extrahiert strukturierte Daten aus einem Dokument via KI',
    zones: ['Z2'],
    module: 'MOD-03',
    risk_level: 'high',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: 'CONSENT_EXTRACTION',
    roles_allowed: ['org_admin'],
    data_scopes_read: ['storage_nodes', 'documents'],
    data_scopes_write: ['extracted_data'],
    side_effects: ['modifies_extracted_data', 'credits_consumed'],
    preconditions: ['document_exists', 'document_readable'],
    postconditions: ['extraction_logged', 'billing_event_created'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_page',
    cost_hint_cents: 2,
    api_contract: { type: 'edge_function', endpoint: 'sot-document-parser' },
    ui_entrypoints: ['/portal/dms'],
    audit_event_type: 'ARM_DOC_EXTRACT',
    status: 'active',
  },

  // ===========================================================================
  // MOD-04: IMMOBILIEN ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD04.EXPLAIN_MODULE',
    title_de: 'Immobilien-Modul erklären',
    description_de: 'Erklärt die Funktionen des Immobilien-Moduls',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['knowledge_base'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/immobilien'],
    audit_event_type: 'ARM_EXPLAIN_MOD04',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD04.VALIDATE_PROPERTY',
    title_de: 'Datenqualität prüfen',
    description_de: 'Analysiert Vollständigkeit und Qualität der Immobiliendaten',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['properties', 'units', 'leases'],
    data_scopes_write: [],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 1,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/immobilien'],
    audit_event_type: 'ARM_VALIDATE_PROPERTY',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD04.CREATE_PROPERTY',
    title_de: 'Immobilie anlegen',
    description_de: 'Erstellt einen neuen Immobilien-Datensatz',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'high',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: ['org_admin'],
    data_scopes_read: [],
    data_scopes_write: ['properties'],
    side_effects: ['modifies_properties'],
    preconditions: ['user_is_org_admin'],
    postconditions: ['property_created', 'audit_logged'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-property-crud' },
    ui_entrypoints: ['/portal/immobilien/portfolio'],
    audit_event_type: 'ARM_PROPERTY_CREATE',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD04.CREATE_UNIT',
    title_de: 'Einheit anlegen',
    description_de: 'Erstellt eine neue Einheit für eine Immobilie',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'high',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: ['org_admin'],
    data_scopes_read: ['properties'],
    data_scopes_write: ['units'],
    side_effects: ['modifies_units'],
    preconditions: ['property_exists', 'user_is_org_admin'],
    postconditions: ['unit_created', 'audit_logged'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-property-crud' },
    ui_entrypoints: ['/portal/immobilien'],
    audit_event_type: 'ARM_UNIT_CREATE',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD04.CALCULATE_KPI',
    title_de: 'KPIs berechnen',
    description_de: 'Berechnet Rendite, Cashflow und andere Kennzahlen',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['properties', 'units', 'leases'],
    data_scopes_write: [],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 1,
    api_contract: { type: 'tool_call', endpoint: null, tool_name: 'calculate_investment' },
    ui_entrypoints: ['/portal/immobilien'],
    audit_event_type: 'ARM_CALCULATE_KPI',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD04.LINK_DOCUMENTS',
    title_de: 'Dokumente verknüpfen',
    description_de: 'Verknüpft Dokumente mit der Immobilienakte',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: ['org_admin', 'org_member'],
    data_scopes_read: ['properties', 'storage_nodes'],
    data_scopes_write: ['document_links'],
    side_effects: ['modifies_document_links'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'rpc', endpoint: 'link_document_to_entity' },
    ui_entrypoints: ['/portal/immobilien'],
    audit_event_type: 'ARM_DOC_LINK',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD04.DATA_QUALITY_CHECK',
    title_de: 'Vollständigkeit prüfen',
    description_de: 'Zeigt Checkliste der fehlenden Daten und Dokumente',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['properties', 'units', 'documents'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/immobilien'],
    audit_event_type: 'ARM_DATA_QUALITY',
    status: 'active',
  },

  // ===========================================================================
  // MOD-07: FINANZIERUNG ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD07.EXPLAIN_SELBSTAUSKUNFT',
    title_de: 'Selbstauskunft erklären',
    description_de: 'Erklärt welche Daten benötigt werden und warum',
    zones: ['Z2'],
    module: 'MOD-07',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['knowledge_base'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/finanzierung'],
    audit_event_type: 'ARM_EXPLAIN_SELBSTAUSKUNFT',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD07.DOC_CHECKLIST',
    title_de: 'Dokument-Checkliste',
    description_de: 'Zeigt welche Dokumente für die Finanzierung benötigt werden',
    zones: ['Z2'],
    module: 'MOD-07',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['applicant_profiles', 'documents'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/finanzierung'],
    audit_event_type: 'ARM_DOC_CHECKLIST',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD07.PREPARE_EXPORT',
    title_de: 'Export vorbereiten',
    description_de: 'Bereitet das Finanzierungspaket für den Export vor',
    zones: ['Z2'],
    module: 'MOD-07',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['applicant_profiles', 'documents', 'finance_requests'],
    data_scopes_write: ['export_packages'],
    side_effects: ['modifies_export_packages'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'edge_function', endpoint: 'sot-docs-export' },
    ui_entrypoints: ['/portal/finanzierung'],
    audit_event_type: 'ARM_PREPARE_EXPORT',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD07.VALIDATE_READINESS',
    title_de: 'Finanzierungsbereitschaft',
    description_de: 'Analysiert ob alle Voraussetzungen für eine Finanzierungsanfrage erfüllt sind',
    zones: ['Z2'],
    module: 'MOD-07',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['applicant_profiles', 'documents'],
    data_scopes_write: [],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 2,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/finanzierung'],
    audit_event_type: 'ARM_VALIDATE_READINESS',
    status: 'active',
  },

  // ===========================================================================
  // MOD-08: INVESTMENT-SUCHE ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD08.ANALYZE_FAVORITE',
    title_de: 'Favorit analysieren',
    description_de: 'Analysiert ein Objekt aus den Favoriten mit Detailbewertung',
    zones: ['Z2'],
    module: 'MOD-08',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['favorites', 'listings'],
    data_scopes_write: [],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 3,
    api_contract: { type: 'tool_call', endpoint: null, tool_name: 'calculate_investment' },
    ui_entrypoints: ['/portal/investments'],
    audit_event_type: 'ARM_ANALYZE_FAVORITE',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD08.RUN_SIMULATION',
    title_de: 'Investment-Simulation',
    description_de: 'Führt eine vollständige Investment-Simulation durch',
    zones: ['Z2'],
    module: 'MOD-08',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 2,
    api_contract: { type: 'edge_function', endpoint: 'sot-investment-engine' },
    ui_entrypoints: ['/portal/investments/simulation'],
    audit_event_type: 'ARM_RUN_SIMULATION',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD08.CREATE_MANDATE',
    title_de: 'Suchmandat anlegen',
    description_de: 'Erstellt ein neues Suchmandat für die Akquise',
    zones: ['Z2'],
    module: 'MOD-08',
    risk_level: 'high',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['applicant_profiles'],
    data_scopes_write: ['acq_mandates'],
    side_effects: ['modifies_acq_mandates'],
    preconditions: ['user_authenticated'],
    postconditions: ['mandate_created', 'audit_logged'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'rpc', endpoint: 'create_mandate' },
    ui_entrypoints: ['/portal/investments/mandat'],
    audit_event_type: 'ARM_CREATE_MANDATE',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD08.WEB_RESEARCH',
    title_de: 'Standort-Recherche',
    description_de: 'Recherchiert Standortinformationen aus öffentlichen Quellen',
    zones: ['Z2'],
    module: 'MOD-08',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: ['external_api_call', 'credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 5,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal/investments'],
    audit_event_type: 'ARM_WEB_RESEARCH',
    status: 'active',
  },

  // ===========================================================================
  // MOD-13: PROJEKTE (BAUTRÄGER) ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD13.CREATE_DEV_PROJECT',
    title_de: 'Bauträgerprojekt anlegen',
    description_de: 'Erstellt ein neues Bauträgerprojekt aus hochgeladenen Dokumenten (Exposé, Preisliste) via KI-Analyse',
    zones: ['Z2'],
    module: 'MOD-13',
    risk_level: 'high',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['tenant_documents'],
    data_scopes_write: ['dev_projects', 'dev_project_units', 'storage_nodes'],
    side_effects: ['modifies_dev_projects', 'creates_storage_tree', 'credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 500,
    api_contract: { type: 'edge_function', endpoint: 'sot-project-intake' },
    ui_entrypoints: ['/portal/projekte'],
    audit_event_type: 'ARM_CREATE_DEV_PROJECT',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD13.EXPLAIN_MODULE',
    title_de: 'Projekte-Modul erklären',
    description_de: 'Erklärt Funktionsumfang und Golden Path des Projekte-Moduls (MOD-13)',
    zones: ['Z2'],
    module: 'MOD-13',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['knowledge_base'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/projekte'],
    audit_event_type: 'ARM_EXPLAIN_MOD13',
    status: 'active',
  },

  // ===========================================================================
  // MOD-00: DASHBOARD WIDGET ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD00.CREATE_REMINDER',
    title_de: 'Erinnerung erstellen',
    description_de: 'Erstellt eine zeitbasierte Erinnerung als Widget',
    zones: ['Z2'],
    module: 'MOD-00',
    risk_level: 'low',
    execution_mode: 'execute', // K3-konform: low risk + free + interne Widget-Writes (keine externen Konsequenzen)
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['widgets'],
    side_effects: ['modifies_widgets'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_CREATE_REMINDER',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD00.CREATE_NOTE',
    title_de: 'Notiz erstellen',
    description_de: 'Erstellt eine schnelle Notiz als Widget',
    zones: ['Z2'],
    module: 'MOD-00',
    risk_level: 'low',
    execution_mode: 'execute', // K3-konform: low risk + free + interne Widget-Writes
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['widgets'],
    side_effects: ['modifies_widgets'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_CREATE_NOTE',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD00.CREATE_IDEA',
    title_de: 'Idee festhalten',
    description_de: 'Speichert eine kreative Idee als Widget',
    zones: ['Z2'],
    module: 'MOD-00',
    risk_level: 'low',
    execution_mode: 'execute', // K3-konform: low risk + free + interne Widget-Writes
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['widgets'],
    side_effects: ['modifies_widgets'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_CREATE_IDEA',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD00.CREATE_PROJECT',
    title_de: 'Projekt anlegen',
    description_de: 'Erstellt einen Projekt-Tracker als Widget',
    zones: ['Z2'],
    module: 'MOD-00',
    risk_level: 'low',
    execution_mode: 'execute', // K3-konform: low risk + free + interne Widget-Writes
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['widgets'],
    side_effects: ['modifies_widgets'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_CREATE_PROJECT',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD00.CREATE_TASK',
    title_de: 'Aufgabe erstellen',
    description_de: 'Erstellt eine To-Do-Aufgabe als Widget',
    zones: ['Z2'],
    module: 'MOD-00',
    risk_level: 'low',
    execution_mode: 'execute', // K3-konform: low risk + free + interne Widget-Writes
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['widgets'],
    side_effects: ['modifies_widgets'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_CREATE_TASK',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD00.CREATE_RESEARCH',
    title_de: 'Recherche erstellen',
    description_de: 'Erstellt eine Web-Recherche als Widget',
    zones: ['Z2'],
    module: 'MOD-00',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['widgets'],
    side_effects: ['modifies_widgets', 'external_api_call', 'credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 5,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_CREATE_RESEARCH',
    status: 'active',
  },

  // ===========================================================================
  // KB: KNOWLEDGE BASE ACTIONS (Phase 6.4)
  // ===========================================================================
  {
    action_code: 'ARM.KB.CREATE_RESEARCH_MEMO',
    title_de: 'Research Memo erstellen',
    description_de: 'Erstellt ein Recherche-Memo für die Knowledge Base (nur Draft)',
    zones: ['Z2'],
    module: null,
    risk_level: 'medium',
    execution_mode: 'draft_only', // K4: Only creates draft, no SSOT writes
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: ['armstrong_knowledge_items'], // Draft only
    side_effects: ['creates_kb_draft', 'credits_consumed'],
    preconditions: ['user_authenticated'],
    postconditions: ['kb_draft_created', 'requires_review'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 300, // 6 Credits × 50 Cent
    credits_estimate: 6,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_KB_RESEARCH_MEMO',
    status: 'active',
  },
  {
    action_code: 'ARM.KB.SUGGEST_KB_ITEM_FROM_CHAT',
    title_de: 'KB-Artikel vorschlagen',
    description_de: 'Schlägt einen neuen Knowledge Base Artikel basierend auf Chat-Kontext vor (nur Draft)',
    zones: ['Z2'],
    module: null,
    risk_level: 'low',
    execution_mode: 'draft_only',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['knowledge_base'],
    data_scopes_write: ['armstrong_knowledge_items'],
    side_effects: ['creates_kb_draft', 'credits_consumed'],
    preconditions: ['user_authenticated', 'chat_context_available'],
    postconditions: ['kb_draft_created', 'requires_review'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 100, // 2 Credits × 50 Cent
    credits_estimate: 2,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_KB_SUGGEST_ITEM',
    status: 'active',
  },
  {
    action_code: 'ARM.KB.BUILD_SALES_SCRIPT_VARIANTS',
    title_de: 'Verkaufsskript-Varianten erstellen',
    description_de: 'Generiert verschiedene Varianten eines Verkaufsskripts (nur Draft)',
    zones: ['Z2'],
    module: null,
    risk_level: 'low',
    execution_mode: 'draft_only',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['knowledge_base'],
    data_scopes_write: ['armstrong_knowledge_items'],
    side_effects: ['creates_kb_draft', 'credits_consumed'],
    preconditions: ['user_authenticated', 'base_script_provided'],
    postconditions: ['kb_draft_created', 'requires_review'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 150, // 3 Credits × 50 Cent
    credits_estimate: 3,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal', '/admin/armstrong/knowledge'],
    audit_event_type: 'ARM_KB_SALES_SCRIPT',
    status: 'active',
  },

  // ===========================================================================
  // PACK A: NEW GLOBAL ACTIONS (Phase 6 Content Blueprints)
  // ===========================================================================
  {
    action_code: 'ARM.GLOBAL.SUMMARIZE_TEXT',
    title_de: 'Text zusammenfassen',
    description_de: 'Fasst einen Text strukturiert zusammen (mit Disclaimer bei tax/legal)',
    zones: ['Z2'],
    module: null,
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: [],
    data_scopes_write: [],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 100, // 2 Credits × 50 Cent
    credits_estimate: 2,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_SUMMARIZE_TEXT',
    status: 'active',
  },
  {
    action_code: 'ARM.GLOBAL.DRAFT_MESSAGE',
    title_de: 'Nachricht entwerfen',
    description_de: 'Erstellt einen Entwurf für eine E-Mail oder Nachricht (ohne Senden)',
    zones: ['Z2'],
    module: null,
    risk_level: 'medium',
    execution_mode: 'draft_only',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['contacts'],
    data_scopes_write: [],
    side_effects: ['creates_draft', 'credits_consumed'],
    preconditions: ['user_authenticated'],
    postconditions: ['draft_available_for_review'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 100, // 2 Credits × 50 Cent
    credits_estimate: 2,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal', '/portal/office'],
    audit_event_type: 'ARM_DRAFT_MESSAGE',
    status: 'active',
  },

  // ===========================================================================
  // PACK B: NEW WIDGET ACTION (Phase 6 Content Blueprints)
  // ===========================================================================
  {
    action_code: 'ARM.MOD00.ARCHIVE_WIDGET',
    title_de: 'Widget archivieren',
    description_de: 'Archiviert ein bestehendes Dashboard-Widget',
    zones: ['Z2'],
    module: 'MOD-00',
    risk_level: 'low',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['widgets'],
    data_scopes_write: ['widgets'],
    side_effects: ['modifies_widgets'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: 0,
    credits_estimate: 0,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal'],
    audit_event_type: 'ARM_ARCHIVE_WIDGET',
    status: 'active',
  },

  // ===========================================================================
  // PACK C: NEW DMS ACTION (Phase 6 Content Blueprints)
  // ===========================================================================
  {
    action_code: 'ARM.MOD03.DOC_CONFIDENCE_REVIEW_ASSIST',
    title_de: 'Extraktions-Review unterstützen',
    description_de: 'Erklärt Needs-Review-Status und listet Confidence/Fields auf',
    zones: ['Z2'],
    module: 'MOD-03',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['storage_nodes', 'extracted_data'],
    data_scopes_write: [],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 100, // 2 Credits × 50 Cent
    credits_estimate: 2,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/dms'],
    audit_event_type: 'ARM_DOC_CONFIDENCE_REVIEW',
    status: 'active',
  },

  // ===========================================================================
  // PACK D: NEW PROPERTY ACTIONS (Phase 6 Content Blueprints)
  // ===========================================================================
  {
    action_code: 'ARM.MOD04.SUGGEST_DOCUMENTS_CHECKLIST',
    title_de: 'Dokumenten-Checkliste vorschlagen',
    description_de: 'Schlägt vor, welche Dokumente für Bewertung/Finanzierung/Verkauf fehlen',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['properties', 'documents', 'knowledge_base'],
    data_scopes_write: [],
    side_effects: ['credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 100, // 2 Credits × 50 Cent
    credits_estimate: 2,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/immobilien'],
    audit_event_type: 'ARM_SUGGEST_DOC_CHECKLIST',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD04.GENERATE_EXPOSE_DRAFT',
    title_de: 'Exposé-Entwurf erstellen',
    description_de: 'Generiert einen Exposé-Textentwurf für internes Review (ohne Publizieren)',
    zones: ['Z2'],
    module: 'MOD-04',
    risk_level: 'medium',
    execution_mode: 'draft_only',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['properties', 'units', 'documents'],
    data_scopes_write: [],
    side_effects: ['creates_draft', 'credits_consumed'],
    preconditions: ['property_exists', 'user_authenticated'],
    postconditions: ['draft_available_for_review'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 150, // 3 Credits × 50 Cent
    credits_estimate: 3,
    api_contract: { type: 'edge_function', endpoint: 'sot-armstrong-advisor' },
    ui_entrypoints: ['/portal/immobilien'],
    audit_event_type: 'ARM_GENERATE_EXPOSE_DRAFT',
    status: 'active',
  },

  // ===========================================================================
  // MOD-21: WEBSITE BUILDER ACTIONS
  // ===========================================================================
  {
    action_code: 'ARM.MOD21.GENERATE_WEBSITE',
    title_de: 'Website generieren',
    description_de: 'Erstellt eine komplette Website-Struktur mit KI-generierten Texten basierend auf Firmenprofil und Design-Template',
    zones: ['Z2'],
    module: 'MOD-21',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['tenant_websites'],
    data_scopes_write: ['tenant_websites', 'website_pages', 'website_sections'],
    side_effects: ['external_api_call', 'credits_consumed'],
    preconditions: ['user_authenticated'],
    postconditions: ['website_generated', 'billing_event_created'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 250,
    credits_estimate: 5,
    api_contract: { type: 'edge_function', endpoint: 'sot-website-ai-generate' },
    ui_entrypoints: ['/portal/website-builder'],
    audit_event_type: 'ARM_WEBSITE_GENERATE',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD21.UPDATE_SECTION',
    title_de: 'Section-Inhalt ändern',
    description_de: 'Ändert den Inhalt einer Website-Section per KI basierend auf Freitext-Anweisung',
    zones: ['Z2'],
    module: 'MOD-21',
    risk_level: 'low',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['website_sections'],
    data_scopes_write: ['website_sections'],
    side_effects: ['external_api_call', 'credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 50,
    credits_estimate: 1,
    api_contract: { type: 'edge_function', endpoint: 'sot-website-update-section' },
    ui_entrypoints: ['/portal/website-builder'],
    audit_event_type: 'ARM_WEBSITE_UPDATE_SECTION',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD21.ADD_SECTION',
    title_de: 'Section hinzufügen',
    description_de: 'Fügt eine neue Section zur Website hinzu mit KI-generierten Inhalten',
    zones: ['Z2'],
    module: 'MOD-21',
    risk_level: 'low',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['website_sections'],
    data_scopes_write: ['website_sections'],
    side_effects: ['external_api_call', 'credits_consumed'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 50,
    credits_estimate: 1,
    api_contract: { type: 'edge_function', endpoint: 'sot-website-update-section' },
    ui_entrypoints: ['/portal/website-builder'],
    audit_event_type: 'ARM_WEBSITE_ADD_SECTION',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD21.REMOVE_SECTION',
    title_de: 'Section entfernen',
    description_de: 'Entfernt eine Section von der Website',
    zones: ['Z2'],
    module: 'MOD-21',
    risk_level: 'low',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['website_sections'],
    data_scopes_write: ['website_sections'],
    side_effects: ['modifies_website_sections'],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/website-builder'],
    audit_event_type: 'ARM_WEBSITE_REMOVE_SECTION',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD21.CHANGE_TEMPLATE',
    title_de: 'Design-Template wechseln',
    description_de: 'Wechselt das Design-Template der Website (Farben, Schriftart, Layout-Stil)',
    zones: ['Z2'],
    module: 'MOD-21',
    risk_level: 'low',
    execution_mode: 'execute',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['tenant_websites'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/website-builder'],
    audit_event_type: 'ARM_WEBSITE_CHANGE_TEMPLATE',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD21.PUBLISH',
    title_de: 'Website veröffentlichen',
    description_de: 'Erstellt einen Publish-Snapshot und macht die Website öffentlich erreichbar',
    zones: ['Z2'],
    module: 'MOD-21',
    risk_level: 'medium',
    execution_mode: 'execute_with_confirmation',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['tenant_websites', 'hosting_contracts'],
    data_scopes_write: ['website_versions', 'tenant_websites'],
    side_effects: ['credits_consumed', 'public_exposure'],
    preconditions: ['hosting_contract_active', 'sections_exist'],
    postconditions: ['version_created', 'billing_event_created'],
    version: '1.0.0',
    cost_model: 'metered',
    cost_unit: 'per_call',
    cost_hint_cents: 500,
    credits_estimate: 10,
    api_contract: { type: 'edge_function', endpoint: 'sot-website-publish' },
    ui_entrypoints: ['/portal/website-builder'],
    audit_event_type: 'ARM_WEBSITE_PUBLISH',
    status: 'active',
  },
  {
    action_code: 'ARM.MOD21.PREVIEW',
    title_de: 'Website-Vorschau',
    description_de: 'Zeigt eine Vorschau der aktuellen Website-Entwurfsversion',
    zones: ['Z2'],
    module: 'MOD-21',
    risk_level: 'low',
    execution_mode: 'readonly',
    requires_consent_code: null,
    roles_allowed: [],
    data_scopes_read: ['tenant_websites', 'website_sections'],
    data_scopes_write: [],
    side_effects: [],
    version: '1.0.0',
    cost_model: 'free',
    cost_unit: null,
    cost_hint_cents: null,
    api_contract: { type: 'internal', endpoint: null },
    ui_entrypoints: ['/portal/website-builder'],
    audit_event_type: 'ARM_WEBSITE_PREVIEW',
    status: 'active',
  },
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get all actions available for a specific zone
 */
export function getActionsForZone(zone: ArmstrongZone): ArmstrongActionV2[] {
  return armstrongActions.filter(action => 
    action.zones.includes(zone) && action.status === 'active'
  );
}

/**
 * Get all actions for a specific module
 */
export function getActionsForModule(moduleCode: string): ArmstrongActionV2[] {
  return armstrongActions.filter(action => 
    action.module === moduleCode && action.status === 'active'
  );
}

/**
 * Get action by code
 */
export function getAction(actionCode: string): ArmstrongActionV2 | undefined {
  return armstrongActions.find(action => action.action_code === actionCode);
}

/**
 * Check if an action requires confirmation based on execution_mode
 */
export function requiresConfirmation(actionCode: string): boolean {
  const action = getAction(actionCode);
  if (!action) return true; // Default to safe
  return action.execution_mode === 'execute_with_confirmation' || 
         action.execution_mode === 'draft_only';
}

/**
 * Check if action is allowed in Zone 3
 */
export function isZone3Action(actionCode: string): boolean {
  return ZONE3_ALLOWED_ACTION_CODES.includes(actionCode as Zone3ActionCode);
}

/**
 * Get all metered actions (for billing dashboard)
 */
export function getMeteredActions(): ArmstrongActionV2[] {
  return armstrongActions.filter(action => action.cost_model === 'metered');
}

/**
 * Filter actions by role
 */
export function filterActionsByRole(
  actions: ArmstrongActionV2[], 
  userRoles: string[]
): ArmstrongActionV2[] {
  return actions.filter(action => {
    // Empty roles_allowed means all authenticated users can access
    if (action.roles_allowed.length === 0) return true;
    // Check if user has any of the required roles
    return action.roles_allowed.some(role => userRoles.includes(role));
  });
}

/**
 * Get actions by execution mode
 */
export function getActionsByExecutionMode(mode: ExecutionMode): ArmstrongActionV2[] {
  return armstrongActions.filter(action => action.execution_mode === mode);
}

/**
 * Get high-risk actions (for governance review)
 */
export function getHighRiskActions(): ArmstrongActionV2[] {
  return armstrongActions.filter(action => action.risk_level === 'high');
}

/**
 * Legacy compatibility: map requires_confirmation to execution_mode
 * @deprecated Use execution_mode directly
 */
export function getRequiresConfirmation(action: ArmstrongActionV2): boolean {
  return action.execution_mode === 'execute_with_confirmation';
}
