/**
 * SOT-ACQ-OUTBOUND
 * 
 * Sends outreach emails via Resend API with routing tokens for inbound tracking
 */
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface SendRequest {
  mandateId: string;
  contactId?: string;
  contactIds?: string[];
  templateCode: string;
  variables: Record<string, string>;
  bulk?: boolean;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    if (!RESEND_API_KEY) {
      // Queue message without sending if no API key
      console.warn('RESEND_API_KEY not configured - queuing message only');
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const body: SendRequest = await req.json();
    const { mandateId, contactId, contactIds, templateCode, variables, bulk } = body;

    // Get mandate for context
    const { data: mandate } = await supabase
      .from('acq_mandates')
      .select('code, profile_text_email')
      .eq('id', mandateId)
      .single();

    // Get template
    const { data: template, error: templateError } = await supabase
      .from('acq_email_templates')
      .select('*')
      .eq('code', templateCode)
      .single();

    if (templateError || !template) {
      throw new Error(`Template ${templateCode} not found`);
    }

    // Determine contacts to send to
    const targetContactIds = bulk && contactIds ? contactIds : contactId ? [contactId] : [];

    if (targetContactIds.length === 0) {
      throw new Error('No contacts specified');
    }

    // Get contacts
    const { data: contacts, error: contactError } = await supabase
      .from('contacts')
      .select('id, first_name, last_name, email, company')
      .in('id', targetContactIds);

    if (contactError || !contacts?.length) {
      throw new Error('Contacts not found');
    }

    const results = [];

    for (const contact of contacts) {
      if (!contact.email) {
        console.warn(`Contact ${contact.id} has no email, skipping`);
        continue;
      }

      // Render template
      const allVariables = {
        ...variables,
        firstName: contact.first_name || '',
        lastName: contact.last_name || '',
        company: contact.company || '',
        mandateCode: mandate?.code || '',
      };

      let subject = template.subject_template;
      let bodyHtml = template.body_html_template;
      let bodyText = template.body_text_template || '';

      for (const [key, value] of Object.entries(allVariables)) {
        const placeholder = `{{${key}}}`;
        subject = subject.replace(new RegExp(placeholder, 'g'), value);
        bodyHtml = bodyHtml.replace(new RegExp(placeholder, 'g'), value);
        bodyText = bodyText.replace(new RegExp(placeholder, 'g'), value);
      }

      // Create outbound record (routing_token auto-generated by trigger)
      const { data: outbound, error: insertError } = await supabase
        .from('acq_outbound_messages')
        .insert([{
          mandate_id: mandateId,
          contact_id: contact.id,
          template_code: templateCode,
          subject,
          body_html: bodyHtml,
          body_text: bodyText,
          status: RESEND_API_KEY ? 'sending' : 'queued',
        }])
        .select()
        .single();

      if (insertError) {
        console.error('Failed to create outbound record:', insertError);
        continue;
      }

      // Send via Resend if API key exists
      if (RESEND_API_KEY) {
        try {
          const replyTo = `acq+${mandateId}+${contact.id}@incoming.systemofatown.de`;

          const resendResponse = await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${RESEND_API_KEY}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              from: 'System of a Town <noreply@systemofatown.de>',
              to: [contact.email],
              reply_to: replyTo,
              subject,
              html: bodyHtml,
              text: bodyText,
              headers: {
                'X-Acq-Token': outbound.routing_token,
              },
            }),
          });

          const resendData = await resendResponse.json();

          if (resendResponse.ok) {
            await supabase
              .from('acq_outbound_messages')
              .update({
                status: 'sent',
                resend_message_id: resendData.id,
                sent_at: new Date().toISOString(),
              })
              .eq('id', outbound.id);

            results.push({ contactId: contact.id, status: 'sent', messageId: resendData.id });
          } else {
            await supabase
              .from('acq_outbound_messages')
              .update({
                status: 'failed',
                error_message: JSON.stringify(resendData),
              })
              .eq('id', outbound.id);

            results.push({ contactId: contact.id, status: 'failed', error: resendData });
          }
        } catch (sendError) {
          console.error('Resend API error:', sendError);
          await supabase
            .from('acq_outbound_messages')
            .update({
              status: 'failed',
              error_message: String(sendError),
            })
            .eq('id', outbound.id);

          results.push({ contactId: contact.id, status: 'failed', error: String(sendError) });
        }
      } else {
        results.push({ contactId: contact.id, status: 'queued' });
      }

      // Log audit event
      await supabase.from('acq_mandate_events').insert([{
        mandate_id: mandateId,
        event_type: 'email_sent',
        payload: {
          contact_id: contact.id,
          template_code: templateCode,
          outbound_id: outbound.id,
        },
      }]);
    }

    return new Response(
      JSON.stringify({ success: true, results }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in sot-acq-outbound:', error);
    return new Response(
      JSON.stringify({ success: false, error: String(error) }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
